export const CURRENCY = {
    north_america: [
        {
            symbol: "$",
            name: "US Dollar",
            symbol_native: "$",
            decimal_digits: 2,
            rounding: 0,
            code: "USD",
            name_plural: "US dollars",
        },
        {
            symbol: "CA$",
            name: "Canadian Dollar",
            symbol_native: "$",
            decimal_digits: 2,
            rounding: 0,
            code: "CAD",
            name_plural: "Canadian dollars",
        },
        {
            symbol: "BZ$",
            name: "Belize Dollar",
            symbol_native: "$",
            decimal_digits: 2,
            rounding: 0,
            code: "BZD",
            name_plural: "Belize dollars",
        },
        {
            symbol: "₡",
            name: "Costa Rican Colón",
            symbol_native: "₡",
            decimal_digits: 0,
            rounding: 0,
            code: "CRC",
            name_plural: "Costa Rican colóns",
        },
        {
            symbol: "RD$",
            name: "Dominican Peso",
            symbol_native: "RD$",
            decimal_digits: 2,
            rounding: 0,
            code: "DOP",
            name_plural: "Dominican pesos",
        },
        {
            symbol: "GTQ",
            name: "Guatemalan Quetzal",
            symbol_native: "Q",
            decimal_digits: 2,
            rounding: 0,
            code: "GTQ",
            name_plural: "Guatemalan quetzals",
        },
        {
            symbol: "HNL",
            name: "Honduran Lempira",
            symbol_native: "L",
            decimal_digits: 2,
            rounding: 0,
            code: "HNL",
            name_plural: "Honduran lempiras",
        },
        {
            symbol: "J$",
            name: "Jamaican Dollar",
            symbol_native: "$",
            decimal_digits: 2,
            rounding: 0,
            code: "JMD",
            name_plural: "Jamaican dollars",
        },
    ],
    south_america: [
        {
            symbol: "AR$",
            name: "Argentine Peso",
            symbol_native: "$",
            decimal_digits: 2,
            rounding: 0,
            code: "ARS",
            name_plural: "Argentine pesos",
        },
        {
            symbol: "Bs",
            name: "Bolivian Boliviano",
            symbol_native: "Bs",
            decimal_digits: 2,
            rounding: 0,
            code: "BOB",
            name_plural: "Bolivian bolivianos",
        },
        {
            symbol: "R$",
            name: "Brazilian Real",
            symbol_native: "R$",
            decimal_digits: 2,
            rounding: 0,
            code: "BRL",
            name_plural: "Brazilian reals",
        },
        {
            symbol: "CL$",
            name: "Chilean Peso",
            symbol_native: "$",
            decimal_digits: 0,
            rounding: 0,
            code: "CLP",
            name_plural: "Chilean pesos",
        },
        {
            symbol: "CO$",
            name: "Colombian Peso",
            symbol_native: "$",
            decimal_digits: 0,
            rounding: 0,
            code: "COP",
            name_plural: "Colombian pesos",
        },
    ],
    europe: [
        {
            symbol: "€",
            name: "Euro",
            symbol_native: "€",
            decimal_digits: 2,
            rounding: 0,
            code: "EUR",
            name_plural: "euros",
        },
        {
            symbol: "ALL",
            name: "Albanian Lek",
            symbol_native: "Lek",
            decimal_digits: 0,
            rounding: 0,
            code: "ALL",
            name_plural: "Albanian lekë",
        },
        {
            symbol: "AMD",
            name: "Armenian Dram",
            symbol_native: "դր.",
            decimal_digits: 0,
            rounding: 0,
            code: "AMD",
            name_plural: "Armenian drams",
        },
        {
            symbol: "man.",
            name: "Azerbaijani Manat",
            symbol_native: "ман.",
            decimal_digits: 2,
            rounding: 0,
            code: "AZN",
            name_plural: "Azerbaijani manats",
        },
        {
            symbol: "KM",
            name: "Bosnia-Herzegovina Convertible Mark",
            symbol_native: "KM",
            decimal_digits: 2,
            rounding: 0,
            code: "BAM",
            name_plural: "Bosnia-Herzegovina convertible marks",
        },
        {
            symbol: "BGN",
            name: "Bulgarian Lev",
            symbol_native: "лв.",
            decimal_digits: 2,
            rounding: 0,
            code: "BGN",
            name_plural: "Bulgarian leva",
        },
        {
            symbol: "Br",
            name: "Belarusian Ruble",
            symbol_native: "руб.",
            decimal_digits: 2,
            rounding: 0,
            code: "BYN",
            name_plural: "Belarusian rubles",
        },
        {
            symbol: "CHF",
            name: "Swiss Franc",
            symbol_native: "CHF",
            decimal_digits: 2,
            rounding: 0.05,
            code: "CHF",
            name_plural: "Swiss francs",
        },
        {
            symbol: "Kč",
            name: "Czech Republic Koruna",
            symbol_native: "Kč",
            decimal_digits: 2,
            rounding: 0,
            code: "CZK",
            name_plural: "Czech Republic korunas",
        },
        {
            symbol: "Dkr",
            name: "Danish Krone",
            symbol_native: "kr",
            decimal_digits: 2,
            rounding: 0,
            code: "DKK",
            name_plural: "Danish kroner",
        },
        {
            symbol: "£",
            name: "British Pound Sterling",
            symbol_native: "£",
            decimal_digits: 2,
            rounding: 0,
            code: "GBP",
            name_plural: "British pounds sterling",
        },
        {
            symbol: "kn",
            name: "Croatian Kuna",
            symbol_native: "kn",
            decimal_digits: 2,
            rounding: 0,
            code: "HRK",
            name_plural: "Croatian kunas",
        },
        {
            symbol: "Ft",
            name: "Hungarian Forint",
            symbol_native: "Ft",
            decimal_digits: 0,
            rounding: 0,
            code: "HUF",
            name_plural: "Hungarian forints",
        },
        {
            symbol: "Ikr",
            name: "Icelandic Króna",
            symbol_native: "kr",
            decimal_digits: 0,
            rounding: 0,
            code: "ISK",
            name_plural: "Icelandic krónur",
        },
    ],
    asia: [
        {
            symbol: "AED",
            name: "United Arab Emirates Dirham",
            symbol_native: "د.إ.",
            decimal_digits: 2,
            rounding: 0,
            code: "AED",
            name_plural: "UAE dirhams",
        },
        {
            symbol: "Af",
            name: "Afghan Afghani",
            symbol_native: "؋",
            decimal_digits: 0,
            rounding: 0,
            code: "AFN",
            name_plural: "Afghan Afghanis",
        },
        {
            symbol: "Tk",
            name: "Bangladeshi Taka",
            symbol_native: "৳",
            decimal_digits: 2,
            rounding: 0,
            code: "BDT",
            name_plural: "Bangladeshi takas",
        },
        {
            symbol: "BD",
            name: "Bahraini Dinar",
            symbol_native: "د.ب.",
            decimal_digits: 3,
            rounding: 0,
            code: "BHD",
            name_plural: "Bahraini dinars",
        },
        {
            symbol: "BN$",
            name: "Brunei Dollar",
            symbol_native: "$",
            decimal_digits: 2,
            rounding: 0,
            code: "BND",
            name_plural: "Brunei dollars",
        },
        {
            symbol: "CN¥",
            name: "Chinese Yuan",
            symbol_native: "CN¥",
            decimal_digits: 2,
            rounding: 0,
            code: "CNY",
            name_plural: "Chinese yuan",
        },
        {
            symbol: "HK$",
            name: "Hong Kong Dollar",
            symbol_native: "$",
            decimal_digits: 2,
            rounding: 0,
            code: "HKD",
            name_plural: "Hong Kong dollars",
        },
        {
            symbol: "Rp",
            name: "Indonesian Rupiah",
            symbol_native: "Rp",
            decimal_digits: 0,
            rounding: 0,
            code: "IDR",
            name_plural: "Indonesian rupiahs",
        },
        {
            symbol: "₪",
            name: "Israeli New Sheqel",
            decimal_digits: 2,
            rounding: 0,
            code: "ILS",
            name_plural: "Israeli new sheqels",
        },
        {
            symbol: "₹",
            name: "Indian Rupee",
            symbol_native: "₹",
            decimal_digits: 2,
            rounding: 0,
            code: "INR",
            name_plural: "Indian rupees",
        },
        {
            symbol: "¥",
            name: "Japanese Yen",
            symbol_native: "￥",
            decimal_digits: 0,
            rounding: 0,
            code: "JPY",
            name_plural: "Japanese yen",
        },
        {
            symbol: "KD",
            name: "Kuwaiti Dinar",
            symbol_native: "د.ك.",
            decimal_digits: 3,
            rounding: 0,
            code: "KWD",
            name_plural: "Kuwaiti dinars",
        },
        {
            symbol: "₭",
            name: "Lao Kip",
            symbol_native: "₭",
            decimal_digits: 0,
            rounding: 0,
            code: "LAK",
            name_plural: "Laos kip",
        },
        {
            symbol: "₨",
            name: "Sri Lankan Rupee",
            symbol_native: "රු.",
            decimal_digits: 2,
            rounding: 0,
            code: "LKR",
            name_plural: "Sri Lankan rupees",
        },
        {
            symbol: "P",
            name: "Mongolian Tugrik",
            symbol_native: "₮",
            decimal_digits: 2,
            rounding: 0,
            code: "MNT",
            name_plural: "Mongolian tugriks",
        },
        {
            symbol: "RM",
            name: "Malaysian Ringgit",
            symbol_native: "RM",
            decimal_digits: 2,
            rounding: 0,
            code: "MYR",
            name_plural: "Malaysian ringgits",
        },
        {
            symbol: "S$",
            name: "Singapore Dollar",
            symbol_native: "$",
            decimal_digits: 2,
            rounding: 0,
            code: "SGD",
            name_plural: "Singapore dollars",
        },
        {
            symbol: "฿",
            name: "Thai Baht",
            symbol_native: "฿",
            decimal_digits: 2,
            rounding: 0,
            code: "THB",
            name_plural: "Thai baht",
        },
        {
            symbol: "₺",
            name: "Turkish Lira",
            symbol_native: "₺",
            decimal_digits: 2,
            rounding: 0,
            code: "TRY",
            name_plural: "Turkish Lira",
        },
        {
            symbol: "NT$",
            name: "New Taiwan Dollar",
            symbol_native: "NT$",
            decimal_digits: 2,
            rounding: 0,
            code: "TWD",
            name_plural: "New Taiwan dollars",
        },
    ],
};
